# Generated by Django 4.2.7 on 2023-12-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_remove_pago_fecha_remove_pago_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talla',
            old_name='nombre',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='talla',
            name='value',
        ),
    ]
